// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjeftsnjdogzdnyvphxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqZWZ0c25qZG9nemRueXZwaHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0Mzk1NzMsImV4cCI6MjA2NDAxNTU3M30.bp55SfMZhWL895Ir3j3qq7OA3J4VQEdkKeJKeOA5Je4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);